name: Post Merge Steps 

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: "read-all"

jobs:

 Post-Merge-Job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      checks: write

    steps:
      - name: "Checkout Current Directory"
        uses: actions/checkout@v3

      - name: "Git Tag and Release"
        uses: abs-wavesight/github-action-workflows/actions/git-tag-release@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      